import { describe, it, expect } from 'vitest';
import { generateIndex } from './generate-index.js';

describe('generateIndex', () => {
	it('emits imports, a typed registry, and the auto-generated header', () => {
		const out = generateIndex(['WelcomeEmail.svelte', 'order-receipt.svelte']);

		expect(out).toContain('// AUTO-GENERATED by @beynar/svelte-email/vite — do not edit.');
		expect(out).toContain(`import { render } from '@beynar/svelte-email';`);
		expect(out).toContain(`import type { ComponentProps } from 'svelte';`);
		expect(out).toContain(`import WelcomeEmail from './WelcomeEmail.svelte';`);
		expect(out).toContain(`import OrderReceipt from './order-receipt.svelte';`);
		expect(out).toContain(
			`welcomeEmail: (props: ComponentProps<typeof WelcomeEmail>) => render(WelcomeEmail, props)`
		);
		expect(out).toContain(
			`orderReceipt: (props: ComponentProps<typeof OrderReceipt>) => render(OrderReceipt, props)`
		);
		expect(out).toContain('export type Emails = typeof emails;');
	});

	it('camelCases snake_case and PascalCase file names consistently', () => {
		const out = generateIndex(['welcome_email.svelte', 'OtpEmail.svelte']);
		expect(out).toContain(`welcomeEmail: (props: ComponentProps<typeof WelcomeEmail>)`);
		expect(out).toContain(`import WelcomeEmail from './welcome_email.svelte';`);
		expect(out).toContain(`otpEmail: (props: ComponentProps<typeof OtpEmail>)`);
		expect(out).toContain(`import OtpEmail from './OtpEmail.svelte';`);
	});

	it('emits a valid minimal file for an empty list', () => {
		const out = generateIndex([]);
		expect(out).toContain('// AUTO-GENERATED by @beynar/svelte-email/vite — do not edit.');
		expect(out).toContain('export const emails = {};');
		expect(out).toContain('export type Emails = typeof emails;');
		// No render import / default imports when there are no entries.
		expect(out).not.toContain(`from '@beynar/svelte-email'`);
		expect(out).not.toContain('=> render(');
	});

	it('ignores non-.svelte entries', () => {
		const out = generateIndex(['welcome.svelte', 'index.ts', 'README.md']);
		expect(out).toContain(`import Welcome from './welcome.svelte';`);
		expect(out).not.toContain('index.ts');
		expect(out).not.toContain('README');
	});

	it('de-dupes colliding keys/identifiers deterministically', () => {
		const out = generateIndex(['welcome.svelte', 'Welcome.svelte']);
		// Both collide on `welcome`/`Welcome`; the second (sorted) gets a `2` suffix.
		expect(out).toContain(`import Welcome from './Welcome.svelte';`);
		expect(out).toContain(`import Welcome2 from './welcome.svelte';`);
		expect(out).toContain(`welcome: (props: ComponentProps<typeof Welcome>)`);
		expect(out).toContain(`welcome2: (props: ComponentProps<typeof Welcome2>)`);
		// Deterministic across runs.
		expect(generateIndex(['welcome.svelte', 'Welcome.svelte'])).toBe(out);
	});

	it('sorts entries by key for stable output', () => {
		const out = generateIndex(['zebra.svelte', 'apple.svelte']);
		expect(out.indexOf('apple:')).toBeLessThan(out.indexOf('zebra:'));
	});

	it('respects the importSource override', () => {
		const out = generateIndex(['welcome.svelte'], { importSource: '$lib/index.js' });
		expect(out).toContain(`import { render } from '$lib/index.js';`);
		expect(out).not.toContain(`from '@beynar/svelte-email'`);
	});
});
