/**
 * Options for {@link generateIndex}.
 */
export interface GenerateIndexOptions {
	/**
	 * Module specifier the generated file imports `render` from.
	 * Defaults to `'@beynar/svelte-email'`.
	 */
	importSource?: string;
}

/** Header comment marking the generated file as machine-written. */
const HEADER = '// AUTO-GENERATED by @beynar/svelte-email/vite — do not edit.';

/**
 * Split a basename (sans `.svelte`) into word tokens.
 *
 * Boundaries are any run of non-alphanumeric characters (`-`, `_`, spaces, …)
 * **and** lower→upper transitions, so `order-receipt`, `order_receipt`, and
 * `OrderReceipt` all tokenize to `['order', 'receipt']`. Leading digits inside a
 * token are kept; empty tokens are dropped.
 */
function tokenize(stem: string): string[] {
	return stem
		.replace(/([a-z0-9])([A-Z])/g, '$1 $2')
		.split(/[^A-Za-z0-9]+/)
		.filter(Boolean);
}

/** `['order','receipt']` → `'orderReceipt'`. */
function toCamelCase(tokens: string[]): string {
	return tokens
		.map((tok, i) => {
			const lower = tok.toLowerCase();
			if (i === 0) return lower;
			return lower.charAt(0).toUpperCase() + lower.slice(1);
		})
		.join('');
}

/** `['order','receipt']` → `'OrderReceipt'`. */
function toPascalCase(tokens: string[]): string {
	return tokens
		.map((tok) => {
			const lower = tok.toLowerCase();
			return lower.charAt(0).toUpperCase() + lower.slice(1);
		})
		.join('');
}

/**
 * Ensure an identifier is a valid JS identifier: prefix a `_` if it starts with
 * a digit, and fall back to `Email`/`email` when tokenization produced nothing.
 */
function safeIdentifier(name: string, fallback: string): string {
	if (name === '') name = fallback;
	if (/^[0-9]/.test(name)) name = `_${name}`;
	return name;
}

/** One resolved registry entry. */
interface Entry {
	/** Original `.svelte` basename, used for the relative import path. */
	fileName: string;
	/** camelCase registry key (unique). */
	key: string;
	/** PascalCase import identifier (unique). */
	ident: string;
}

/**
 * Build the typed registry source from a list of `.svelte` file names (relative
 * to the emails dir).
 *
 * For each name a camelCase key (`order-receipt.svelte` → `orderReceipt`) and a
 * PascalCase import identifier (`OrderReceipt`) are derived. Keys and
 * identifiers are de-duplicated deterministically — colliding entries get a
 * numeric suffix (`welcome`, `welcome2`, …) — and entries are sorted by key for
 * stable output. Each entry returns `Promise<[html, text]>`, matching `render()`.
 *
 * An empty input still yields a valid file with `export const emails = {};`.
 */
export function generateIndex(svelteFileNames: string[], options?: GenerateIndexOptions): string {
	const importSource = options?.importSource ?? '@beynar/svelte-email';

	// Filter to `.svelte` files only and sort by basename for a stable starting
	// order before de-duplication (so suffixes are assigned deterministically).
	const names = svelteFileNames
		.filter((name) => name.endsWith('.svelte'))
		.slice()
		.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));

	const usedKeys = new Set<string>();
	const usedIdents = new Set<string>();
	const entries: Entry[] = [];

	for (const fileName of names) {
		const stem = fileName.slice(0, -'.svelte'.length);
		const tokens = tokenize(stem);

		const baseKey = safeIdentifier(toCamelCase(tokens), 'email');
		const baseIdent = safeIdentifier(toPascalCase(tokens), 'Email');

		// De-dupe key and identifier together so the same numeric suffix lands on
		// both (`welcome`/`Welcome` → `welcome2`/`Welcome2`).
		let key = baseKey;
		let ident = baseIdent;
		let suffix = 2;
		while (usedKeys.has(key) || usedIdents.has(ident)) {
			key = `${baseKey}${suffix}`;
			ident = `${baseIdent}${suffix}`;
			suffix += 1;
		}
		usedKeys.add(key);
		usedIdents.add(ident);

		entries.push({ fileName, key, ident });
	}

	// Sort final entries by key for stable output.
	entries.sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));

	const lines: string[] = [HEADER];

	if (entries.length === 0) {
		lines.push(`import type { ComponentProps } from 'svelte';`);
		lines.push('');
		lines.push('export const emails = {};');
		lines.push('export type Emails = typeof emails;');
		return lines.join('\n') + '\n';
	}

	lines.push(`import { render } from '${importSource}';`);
	lines.push(`import type { ComponentProps } from 'svelte';`);
	for (const { fileName, ident } of entries) {
		lines.push(`import ${ident} from './${fileName}';`);
	}
	lines.push('');
	lines.push('export const emails = {');
	entries.forEach(({ key, ident }, i) => {
		const comma = i === entries.length - 1 ? '' : ',';
		lines.push(
			`\t${key}: (props: ComponentProps<typeof ${ident}>) => render(${ident}, props)${comma}`
		);
	});
	lines.push('};');
	lines.push('export type Emails = typeof emails;');

	return lines.join('\n') + '\n';
}
